version: '3.7'
services:

  db:
    image: postgres:13
    ports:
      - 5432:5432
    networks:
      - shorturl
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=shortdb
      - POSTGRES_HOST_AUTH_METHOD=trust

networks:
  shorturl:
    driver: bridge
